version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
    container_name: yala
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
