# For development usage!
services:
  app:
    build:
      context: .
      target: dev
    command: npm run dev
    container_name: yala
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=yala
      - POSTGRES_PASSWORD=yala
      - POSTGRES_USER=yala
    ports:
      - 5432:5432
    volumes:
      - .db_data:/var/lib/postgresql/data
